### ISSUE TITLE
Milestone: Initial Good Version

### ISSUE THREAD

**Issue by hmans** [hmans/vfx-composer#130]
**Functionality:**

- [x] Implement basic functionality
- [x] Implement module system
- [x] Optimize buffer uploads so only the updated parts get uploaded
- [x] Allow the use of textures (`map` on MeshStandardMaterial et al)
- [x] Find a good pattern for reusing materials/shaders across multiple particle meshes

**Animation Modules:**

- [x] Particle Lifetime
- [x] Animate Scale
- [x] Animate Velocity
- [x] Animate Acceleration
- [x] Animate Color
- [x] Animate Alpha
- [x] Billboard
- [x] Soft Particles: #146
- [x] Rotation
- [x] Rotational Motion (could be the same as rotation after translation?)

**Emitters:**

- [ ] Allow `count` to be a function, executed every time particles are emitted
- [ ] Allow the user to specify the update priority at which to run `useFrame`

**Others:**

- [ ] Provide easing functions (but should probably go into `shader-composer-toybox`?)
- [ ] Default to `MeshStandardMaterial` for the VFXMaterial's baseMaterial
- [ ] `Lifetime` should be `ParticleLifetime`

**Comment by hmans** [comment]
This is for a very old version and no longer relevant.
